import { service } from "./types";

export const dataBasicServicesMonthly: service[] = [
  {
    id: 1,
    type: "starter",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 2.8,
    SSD: 2,
    BandWidth: 10,
    EmailAcounts: 15,
    UnlimitedDatabase: false,
    SubDomains: 4,
    ParkedDomain: 1,
    Websites: 2,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 2,
    type: "standard",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 4.2,
    SSD: 4,
    BandWidth: 14,
    EmailAcounts: 20,
    UnlimitedDatabase: true,
    SubDomains: 6,
    ParkedDomain: 2,
    Websites: 4,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 3,
    type: "suprem",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 7.0,
    SSD: 6,
    BandWidth: 18,
    EmailAcounts: 25,
    UnlimitedDatabase: true,
    SubDomains: 8,
    ParkedDomain: 3,
    Websites: 6,
    SSL: true,
    Softaculous: true,
  },
];

export const dataPremiumServicesMonthly: service[] = [
  {
    id: 1,
    type: "starter",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 14.0,
    SSD: 10,
    BandWidth: 26,
    EmailAcounts: 36,
    UnlimitedDatabase: true,
    SubDomains: 10,
    ParkedDomain: 6,
    Websites: 10,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 2,
    type: "standard",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 18.0,
    SSD: 14,
    BandWidth: 28,
    EmailAcounts: 38,
    UnlimitedDatabase: true,
    SubDomains: 12,
    ParkedDomain: 8,
    Websites: 12,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 3,
    type: "suprem",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 20.0,
    SSD: 16,
    BandWidth: 30,
    EmailAcounts: 40,
    UnlimitedDatabase: true,
    SubDomains: 14,
    ParkedDomain: 10,
    Websites: 14,
    SSL: true,
    Softaculous: true,
  },
];

export const dataBasicServicesYearly: service[] = [
  {
    id: 1,
    type: "starter",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 120.0,
    SSD: 100,
    BandWidth: 260,
    EmailAcounts: 360,
    UnlimitedDatabase: true,
    SubDomains: 100,
    ParkedDomain: 60,
    Websites: 50,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 2,
    type: "standard",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 140.0,
    SSD: 120,
    BandWidth: 280,
    EmailAcounts: 380,
    UnlimitedDatabase: true,
    SubDomains: 120,
    ParkedDomain: 80,
    Websites: 60,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 3,
    type: "suprem",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 160.0,
    SSD: 140,
    BandWidth: 300,
    EmailAcounts: 400,
    UnlimitedDatabase: true,
    SubDomains: 140,
    ParkedDomain: 100,
    Websites: 70,
    SSL: true,
    Softaculous: true,
  },
];

export const dataPremiumServicesYearly: service[] = [
  {
    id: 1,
    type: "starter",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 220.0,
    SSD: 200,
    BandWidth: 360,
    EmailAcounts: 460,
    UnlimitedDatabase: true,
    SubDomains: 200,
    ParkedDomain: 160,
    Websites: 150,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 2,
    type: "standard",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 240.0,
    SSD: 220,
    BandWidth: 380,
    EmailAcounts: 480,
    UnlimitedDatabase: true,
    SubDomains: 220,
    ParkedDomain: 180,
    Websites: 170,
    SSL: true,
    Softaculous: true,
  },
  {
    id: 3,
    type: "suprem",
    desc: "with all your customers via all conversation channels in one central dashboard.",
    price: 260.0,
    SSD: 240,
    BandWidth: 400,
    EmailAcounts: 500,
    UnlimitedDatabase: true,
    SubDomains: 240,
    ParkedDomain: 200,
    Websites: 190,
    SSL: true,
    Softaculous: true,
  },
];
